var sqlite3 = require("sqlite3");
var db = new sqlite3.Database("./forum.db");
// Table Topics added
db.run("INSERT INTO topics (Title, Author, Description, Votes) VALUES ('Introductions', 'Admin', 'Get acquainted with the forum here!', 0);");
db.run("INSERT INTO topics (Title, Author, Description, Votes) VALUES ('Tavern', 'Admin', 'Let us have a meet & greet!', 0);");
db.run("INSERT INTO topics (Title, Author, Description, Votes) VALUES ('Guild', 'Admin', 'The Go-To place to make teams, join teams, and recruit team members.', 0);");
// Comments added
db.run("INSERT INTO comments (Title, Author, Content, City, Topics_ID) VALUES ('Basic Rules', 'Admin', '1. Be respectful, 2. Keep it clean, 3. Never share personal information, 4. No trolling/harrassing, 5. No spamming', 'New York', 1);");
db.run("INSERT INTO comments (Title, Author, Content, City, Topics_ID) VALUES ('Forum Dynamic', 'Admin', 'Welcome to the Hunter Chronicles, fellow hunters. The basics to the forum are as follows: 1. Structure: The forum is composed of topics and comments. Topics hold comments, and comments hold your voice...sort of. 2. Behavior: The way things runs is simple. You create a new topic in order to comment. The topics are recommended to be general while comments are specific. Topics can be created or deleted, but not modified. Comments, however, can be created, modified, and deleted.', 'New York', 1);");
db.run("INSERT INTO comments (Title, Author, Content, City, Topics_ID) VALUES ('Introductions', 'Admin', 'Hello hunters. Before I introduce myself, I encourage anyone who is interested to follow this fun exercise wth me! Share your hunter name, weapon you use/like most, weapon you use/like least, favorite monster to hunt, favorite MH game. Hey guys, I go by Bberry. The weapon I use the most would be the Hammer and Long Sword, and the weapon I use the least are tied between the Hunting Horn and the Lance. My favorite monster to hunt would be the Lagiacrus because it is underwater and it GLOWS! My favorite game is Freedom Unite.', 'New York', 2);");
db.run("INSERT INTO comments (Title, Author, Content, City, Topics_ID) VALUES ('Looking for teams', 'Admin', 'Greetings hunters. As the title suggests, I am interested in joining teams. I could join either hunting or gathering teams. The role I usually take would be the decoy or attacker. Let me know if I am cool enough to join your team LOL.', 'New York', 3);");
